from __future__ import annotations

from itertools import combinations

COLOR_COUNT = 5
TOKEN_TYPES = 6  # 5 color gems + gold
PLAYER_COUNT = 2

TOKEN_LIMIT = 10
TARGET_POINTS = 15
NOBLE_POINTS = 3
MAX_PLIES = 160

BUY_FACEUP_OFFSET = 0
BUY_FACEUP_COUNT = 12
RESERVE_FACEUP_OFFSET = BUY_FACEUP_OFFSET + BUY_FACEUP_COUNT
RESERVE_FACEUP_COUNT = 12
RESERVE_DECK_OFFSET = RESERVE_FACEUP_OFFSET + RESERVE_FACEUP_COUNT
RESERVE_DECK_COUNT = 3
BUY_RESERVED_OFFSET = RESERVE_DECK_OFFSET + RESERVE_DECK_COUNT
BUY_RESERVED_COUNT = 3
TAKE_THREE_OFFSET = BUY_RESERVED_OFFSET + BUY_RESERVED_COUNT
TAKE_THREE_COMBOS = list(combinations(range(COLOR_COUNT), 3))
TAKE_THREE_COUNT = len(TAKE_THREE_COMBOS)
TAKE_TWO_DIFFERENT_OFFSET = TAKE_THREE_OFFSET + TAKE_THREE_COUNT
TAKE_TWO_DIFFERENT_COMBOS = list(combinations(range(COLOR_COUNT), 2))
TAKE_TWO_DIFFERENT_COUNT = len(TAKE_TWO_DIFFERENT_COMBOS)
TAKE_ONE_OFFSET = TAKE_TWO_DIFFERENT_OFFSET + TAKE_TWO_DIFFERENT_COUNT
TAKE_ONE_COLORS = list(range(COLOR_COUNT))
TAKE_ONE_COUNT = len(TAKE_ONE_COLORS)
TAKE_TWO_SAME_OFFSET = TAKE_ONE_OFFSET + TAKE_ONE_COUNT
TAKE_TWO_SAME_COUNT = COLOR_COUNT
CHOOSE_NOBLE_OFFSET = TAKE_TWO_SAME_OFFSET + TAKE_TWO_SAME_COUNT
CHOOSE_NOBLE_COUNT = 3
RETURN_TOKEN_OFFSET = CHOOSE_NOBLE_OFFSET + CHOOSE_NOBLE_COUNT
RETURN_TOKEN_COUNT = TOKEN_TYPES
PASS_ACTION = RETURN_TOKEN_OFFSET + RETURN_TOKEN_COUNT
SPLENDOR_POLICY_DIM = PASS_ACTION + 1

# Label shaping defaults.
DEFAULT_VALUE_MARGIN_WEIGHT = 0.10
DEFAULT_VALUE_MARGIN_SCALE = 15.0
DEFAULT_LABEL_VERSION = "splendor_margin_phase_v1"
DEFAULT_RETURN_PHASE_FACTOR = 0.60

# Feature layout:
# - bank tokens: 6
# - both players (me/op): 2 * (gems6 + bonuses5 + points1 + reserved1 + cards1 + nobles1) = 30
# - visible nobles (3 * (req5 + points1)) = 18
# - tableau cards (12 * (exists1 + tier1 + points1 + bonus5 + costs5)) = 156
# - my reserved cards (3 * 13) = 39
# - opponent reserved cards (3 * 13): faceup-known => real card, deck-reserved => hidden placeholder = 39
# - global scalars: turn_progress + current_player_flag + pending_returns + stage_normal + stage_return + stage_choose_noble = 6
SPLENDOR_INPUT_DIM = 294
FEATURE_TURN_PROGRESS_INDEX = SPLENDOR_INPUT_DIM - 6
FEATURE_CURRENT_PLAYER_INDEX = SPLENDOR_INPUT_DIM - 5
FEATURE_PENDING_RETURNS_INDEX = SPLENDOR_INPUT_DIM - 4
FEATURE_STAGE_NORMAL_INDEX = SPLENDOR_INPUT_DIM - 3
FEATURE_STAGE_RETURN_INDEX = SPLENDOR_INPUT_DIM - 2
FEATURE_STAGE_CHOOSE_NOBLE_INDEX = SPLENDOR_INPUT_DIM - 1
FEATURE_RETURN_PHASE_INDEX = FEATURE_STAGE_RETURN_INDEX

